version: '3'
services:
  app:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - dataBase
    environment:
      MONGO_URI: mongodb://dataBase:27017/task
    networks:
      - app_network

  dataBase:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app_network
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_URI}

networks:
  app_network:
